"""
Commodity Sub-Agent — Pydantic Schemas.

Mirrors the structure of equity/schemas.py for the commodity research domain.
Defines the state, plan, and output models for the commodity pipeline.
"""

from typing import List, Optional, TypedDict, Any, Dict
from pydantic import BaseModel, Field
from langchain_core.messages import BaseMessage


class CommodityPlan(BaseModel):
    """
    Generated by the commodity planner node from the user's natural language request.
    Defines which physical asset and data dimensions to investigate.
    """
    asset: str = Field(
        ...,
        description="The commodity to research. E.g. 'crude oil', 'gold', 'copper'."
    )
    asset_class: str = Field(
        default="",
        description="Broad category. E.g. 'energy', 'precious metals', 'base metals', 'agriculture'."
    )
    primary_exchange: str = Field(
        default="",
        description="Main futures exchange. E.g. 'NYMEX', 'COMEX', 'LME', 'CBOT'."
    )
    time_horizon: str = Field(
        default="12m",
        description="Analysis time horizon. E.g. '12m', '3y'."
    )


class CommoditySection(BaseModel):
    """One section of the commodity research report."""
    title: str = Field(..., description="Section title. E.g. 'Supply & Demand Balance'.")
    content: str = Field(..., description="Markdown content of the section.")


class CommodityReport(BaseModel):
    """
    The final output of the commodity research pipeline.
    Structured equivalent to ResearchReport in equity/schemas.py.
    """
    asset: str
    price_outlook: str = Field(
        ...,
        description="Price direction thesis: bullish / bearish / neutral with rationale."
    )
    key_risks: str = Field(
        ...,
        description="Key upside/downside risks: OPEC decisions, weather, demand shocks, USD."
    )
    supply_demand: CommoditySection = Field(
        ...,
        description="Current and projected supply/demand balance, inventory levels."
    )
    futures_curve: CommoditySection = Field(
        ...,
        description="Spot vs futures structure: contango or backwardation analysis."
    )
    positioning: CommoditySection = Field(
        ...,
        description="CFTC Commitments of Traders (COT): speculative long/short positioning."
    )
    macro_linkages: CommoditySection = Field(
        ...,
        description="USD, interest rates, emerging market demand, and geopolitical drivers."
    )
    references: List[str] = Field(
        default=[],
        description="Data sources: EIA report URLs, CFTC release dates, news URLs."
    )


class CommodityState(TypedDict, total=False):
    """
    LangGraph state for the commodity research pipeline.
    Mirrors the structure of equity/schemas.AgentState.
    """
    messages: List[BaseMessage]
    asset: Optional[str]

    # Plan
    plan: Optional[CommodityPlan]

    # Data file paths
    eia_data_path: Optional[str]             # EIA inventory data as Markdown
    cot_data_path: Optional[str]             # CFTC COT positioning data as Markdown
    futures_data_path: Optional[str]         # Futures curve data as Markdown

    # Research
    research_data: Optional[Dict[str, str]]  # Raw web research keyed by query
    extracted_facts: Optional[str]           # Map-reduced facts for section writing
    research_brief: Optional[Dict[str, str]] # Per-section briefs

    # Working memory
    sections: Optional[Dict[str, CommoditySection]]

    # Output
    source_metadata: Optional[dict]
    report_content: Optional[CommodityReport]
    report_path: Optional[str]
    error: Optional[str]
