from pydantic import BaseModel, Field
from typing import List, TypedDict, Any, Dict
from langchain_core.messages import BaseMessage

from src.shared.node_contracts import NodeResult

class AnalysisPlan(BaseModel):
    """
    Generated by the Planner Agent from user natural language query.
    Directs the execution of the analysis.
    """
    ticker: str = Field(..., description="Stock ticker symbol (e.g., AAPL)")
    subtasks: List[str] = Field(
        default=["technical", "fundamental", "peers"],
        description="List of analysis subtasks to perform"
    )
    peers: List[str] = Field(
        default=[],
        description="List of comparable companies to analyze (e.g., ['MSFT', 'GOOGL'])"
    )

class ResearchSection(BaseModel):
    title: str = Field(..., description="Section Title (e.g. 'Industry Analysis')")
    content: str = Field(..., description="Markdown content with [n] citations")

class ResearchReport(BaseModel):
    """
    The final output generated by the Writer Agent.
    Strictly follows CFA Institute Equity Research standards.
    """
    ticker: str
    target_price: str = Field(..., description="Estimated target price with time horizon (e.g. '$120 (12m)')")
    recommendation: str = Field(..., description="BUY, SELL, or HOLD")
    
    # Generated LAST, presented FIRST
    investment_summary: str = Field(..., description="Executive Summary: Thesis, Valuation Summary, Risks.")
    mispricing_thesis: str = Field(..., description="Why is the security mispriced? What is the market missing?")
    key_catalysts: str = Field(..., description="Events that will unlock value (e.g. Earnings, M&A).")
    
    # Core Analysis Sections (Deep Dives)
    business_description: ResearchSection = Field(..., description="Economics, Drivers, Product Mix")
    industry_analysis: ResearchSection = Field(..., description="Industry Dynamics, Porter's 5 Forces, Moat")
    financial_analysis: ResearchSection = Field(..., description="Quality of Earnings, Reality vs Reported")
    valuation_analysis: ResearchSection = Field(..., description="Relative + Intrinsic/Absolute Valuation")
    investment_risks: ResearchSection = Field(..., description="Operational, Regulatory, Financial Risks")
    esg_analysis: ResearchSection = Field(..., description="Environmental, Social, Governance factors")
    competitor_analysis: ResearchSection = Field(..., description="Deep dive into key competitors, giants, and disruptors.")
    
    references: List[str] = Field(..., description="List of data sources used.")

class AgentState(TypedDict, total=False):
    """
    The state of the agent as it proceeds through the workflow.
    """
    messages: List[BaseMessage]
    ticker: str
    period: str
    
    # File Paths
    market_data_path: str
    chart_path: str
    financials_path: str | None
    peer_data_path: str | None
    categorized_peers: Dict[str, List[str]] # {"Giants": [...], "Peers": [...], "Disruptors": [...]}
    company_profile_path: str | None
    
    # Qualitative Data
    research_data: Dict[str, str] # {"annual_report_risks": "...", "industry_trends": "..."}
    extracted_facts: str # Combined facts from map-reduce synthesis for inference
    research_brief: Dict[str, str] # LLM-synthesized brief per section topic
    
    plan: AnalysisPlan
    
    # Working Memory for Sections
    sections: Dict[str, ResearchSection] # {"Business": SectionObj, "Industry": SectionObj...}
    
    source_metadata: Dict[str, Any]
    last_node_result: NodeResult
    node_results: Dict[str, NodeResult]
    
    report_content: ResearchReport
    report_path: str
    error: str | None
