"""
Macro Sub-Agent — Pydantic Schemas.

Mirrors the structure of equity/schemas.py for the macro research domain.
Defines the state, plan, and output models for the macro pipeline.
"""

from typing import List, Optional, TypedDict, Any, Dict
from pydantic import BaseModel, Field
from langchain_core.messages import BaseMessage


class MacroPlan(BaseModel):
    """
    Generated by the macro planner node from the user's natural language request.
    Defines what economic dimensions to investigate.
    """
    topic: str = Field(
        ...,
        description="The macro/economic topic to research. "
                    "E.g. 'US interest rate outlook', 'China GDP trajectory'."
    )
    countries: List[str] = Field(
        default=[],
        description="Countries or regions to focus on. E.g. ['US', 'EU', 'China']."
    )
    indicators: List[str] = Field(
        default=[],
        description="Economic indicators to pull. E.g. ['CPI', 'Fed Funds Rate', 'Unemployment']."
    )
    time_horizon: str = Field(
        default="12m",
        description="Analysis time horizon. E.g. '12m', '3y'."
    )


class MacroSection(BaseModel):
    """One section of the macro research brief."""
    title: str = Field(..., description="Section title. E.g. 'Interest Rate Dynamics'.")
    content: str = Field(..., description="Markdown content of the section.")


class MacroReport(BaseModel):
    """
    The final output of the macro research pipeline.
    Structured equivalent to ResearchReport in equity/schemas.py.
    """
    topic: str
    outlook: str = Field(
        ...,
        description="One-paragraph investment outlook summary derived from macro analysis."
    )
    key_risks: str = Field(
        ...,
        description="Main macro risks: policy errors, geopolitical shocks, data surprises."
    )
    current_conditions: MacroSection = Field(
        ...,
        description="Current state of key economic indicators with recent data."
    )
    policy_analysis: MacroSection = Field(
        ...,
        description="Central bank policy stance, forward guidance, and market expectations."
    )
    global_linkages: MacroSection = Field(
        ...,
        description="Cross-country spillovers: trade flows, currency dynamics, capital flows."
    )
    scenario_analysis: MacroSection = Field(
        ...,
        description="Bull / base / bear macro scenarios with probability assessments."
    )
    references: List[str] = Field(
        default=[],
        description="Data sources: FRED series IDs, World Bank indicators, news URLs."
    )


class MacroState(TypedDict):
    """
    LangGraph state for the macro research pipeline.
    Mirrors the structure of equity/schemas.AgentState.
    """
    messages: List[BaseMessage]
    topic: Optional[str]

    # Plan
    plan: Optional[MacroPlan]

    # Data file paths
    indicators_path: Optional[str]          # Fetched FRED / World Bank data as Markdown

    # Research
    research_data: Optional[Dict[str, str]] # Raw web research keyed by query
    extracted_facts: Optional[str]          # Map-reduced facts for section writing
    research_brief: Optional[Dict[str, str]]# Per-section briefs

    # Working memory
    sections: Optional[Dict[str, MacroSection]]

    # Output
    source_metadata: Optional[dict]
    report_content: Optional[MacroReport]
    report_path: Optional[str]
    error: Optional[str]
